### ISSUE TITLE
Not connecting to any farcaster ips

### ISSUE THREAD

**Issue by kppercs** [noctisatrae/farseer#1]
Keep getting this error when I run './app' .

* Compiled 
* Connected to DB
Then getting this error 

2024/07/10 13:28:49 ERRO
  Error=
  │ failed to dial: failed to dial 12D3KooWJECuSHn5edaorpufE9ceAoqR5zcAuD4ThoyDzVaz77GV: all dials failed
  │   * [/ip4/3.223.235.209/tcp/2282] failed to negotiate security protocol: read tcp4 172.18.253.67:2282->3.223.235.209:2282: read: connection reset by peer
  
  Platform: Windows WSL

**Comment by noctisatrae** [comment]
Hey thanks for reporting this!

I need a little bit more context, could you provide your `config.toml`?

You're connecting to your own peer? Sometimes some servers won't make the connection, I don't yet know why.

If you have any information on this address, you can tell me and I'll help you as best as I can.

**Comment by kppercs** [comment]
BootstrapPeers = [
   "/dns/lamia.farcaster.xyz/tcp/2282/p2p/12D3KooWJECuSHn5edaorpufE9ceAoqR5zcAuD4ThoyDzVaz77GV",
   "/dns/nemes.farcaster.xyz/tcp/2282/p2p/12D3KooWMQrf6unpGJfLBmTGy3eKTo4cGcXktWRbgMnfbZLXqBbn",
   "/dns/keats.farcaster.xyz/tcp/2282/p2p/12D3KooWBPXFPS656B76tCmbbX6PB4vunmQcd8F38MZjkR88ofBx",
   "/dns/hoyt.farcaster.xyz/tcp/2282/p2p/12D3KooWRnSZUxjVJjbSHhVKpXtvibMarSfLSKDBeMpfVaNm1Joo",
]

How do I use spindle ? If i see IP how do i get DNS resolution URL like above ? i.e. for 173.3.60.161

**Comment by noctisatrae** [comment]
For `173.3.60.161`, you can add that to the bootstrap list:

```
/ip4/173.2.60.161/tcp/2282/p2p/[peerId here]
```

And indeed, the official peers are very random when choosing to whom they connect to.

**Comment by kppercs** [comment]
This issue is resolved. Below worked for me

BootstrapPeers = [
   "/ip4/157.173.206.166/tcp/2282/p2p/12D3KooWLtnpzF2SCWPMSFJWLjE3yQVKzYyQ4yJ64HXu7bJmQ7nF"
]

157.173.206.166 and 12D3KooWLtnpzF2SCWPMSFJWLjE3yQVKzYyQ4yJ64HXu7bJmQ7nF from Spindle link https://farcaster.spindl.xyz/ 

Thanks !

**Comment by noctisatrae** [comment]
Remember to make a custom list by stealing the peer address from the logs :) 

Well played! & have fun
